# Use the official PostgreSQL image as base
FROM postgres:15-alpine

# Copy initialization scripts
COPY ./init.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER=${DB_USER:-postgres}
ENV POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
ENV POSTGRES_DB=${DB_NAME:-myapp_db}